package com.mycompany.ameliafashion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author criss
 */
public class RegistroVentas extends javax.swing.JFrame {
    private static final String BD_URL = "jdbc:mysql://localhost:3306/amelia_fashion";
    private static final String BD_USUARIO = "root";
    private static final String BD_PASSWORD = "";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroVentas.class.getName());

    /**
     * Creates new form RegistroVentas
     */
    public RegistroVentas() {
        initComponents();
        consultarVentas();
    }
     private Connection conectarBD() throws Exception {
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection(BD_URL, BD_USUARIO, BD_PASSWORD);
    }
   private void consultarVentas() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        
        String sql = "SELECT id_venta, id_usuario, id_producto, cantidad, precio FROM compras";
        
        try (Connection con = conectarBD();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            
            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id_venta"),
                    rs.getInt("id_usuario"),
                    rs.getInt("id_producto"),
                    rs.getDouble("cantidad"),
                    rs.getDouble("precio")
                };
                modelo.addRow(fila);
            }
            
            LTexto.setText("Ventas cargadas: " + modelo.getRowCount());
            
        } catch (Exception ex) {
            logger.log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, 
                    "Error al cargar ventas: " + ex.getMessage());
        }
       }
         private void eliminarVenta() {
        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                    "Selecciona una venta para eliminar.");
            return;
        }
        
        int idVenta = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
        int idUsuario = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 1).toString());
        
        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Seguro que deseas eliminar la venta con ID: " + idVenta + "?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION);
        
        if (confirmar == JOptionPane.YES_OPTION) {
            try (Connection con = conectarBD();
                 Statement st = con.createStatement()) {
                
                String sql = "DELETE FROM compras WHERE id_venta = " + idVenta;
                int filasAfectadas = st.executeUpdate(sql);
                
                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(this, 
                            "Venta eliminada correctamente.");
                    consultarVentas(); // Recargar la tabla
                } else {
                    JOptionPane.showMessageDialog(this, 
                            "No se pudo eliminar la venta.");
                }
                
            } catch (Exception ex) {
                logger.log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, 
                        "Error al eliminar venta: " + ex.getMessage());
            }
        }
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TClave = new javax.swing.JTextField();
        LNombre = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        LApellido = new javax.swing.JLabel();
        TApellido = new javax.swing.JTextField();
        LTexto = new javax.swing.JLabel();
        Lclave = new javax.swing.JLabel();
        BEliminar = new javax.swing.JButton();
        Bvolver3 = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LApellido1 = new javax.swing.JLabel();
        TApellido1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TClave.addActionListener(this::TClaveActionPerformed);

        LNombre.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LNombre.setForeground(new java.awt.Color(51, 153, 0));
        LNombre.setText("cantidad");

        TNombre.addActionListener(this::TNombreActionPerformed);

        LApellido.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LApellido.setForeground(new java.awt.Color(51, 153, 0));
        LApellido.setText("precio");

        TApellido.addActionListener(this::TApellidoActionPerformed);

        Lclave.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        Lclave.setForeground(new java.awt.Color(51, 153, 0));
        Lclave.setText("producto");

        BEliminar.setBackground(new java.awt.Color(102, 255, 102));
        BEliminar.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        BEliminar.setForeground(new java.awt.Color(51, 153, 0));
        BEliminar.setText("Eliminar");
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminarMouseClicked(evt);
            }
        });

        Bvolver3.setBackground(new java.awt.Color(153, 255, 153));
        Bvolver3.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        Bvolver3.setForeground(new java.awt.Color(51, 153, 0));
        Bvolver3.setText("Volver");
        Bvolver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bvolver3MouseClicked(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(102, 255, 102));
        BConsultar.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        BConsultar.setForeground(new java.awt.Color(51, 153, 0));
        BConsultar.setText("Consultar");
        BConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BConsultarMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_venta", "id_usuario", "id_producto", "cantidad", "precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addPropertyChangeListener(this::jTable1PropertyChange);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        LApellido1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LApellido1.setForeground(new java.awt.Color(51, 153, 0));
        LApellido1.setText("fecha");

        TApellido1.addActionListener(this::TApellido1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bvolver3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BEliminar)
                                .addGap(64, 64, 64)
                                .addComponent(BConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LApellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(64, 64, 64))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Lclave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TClave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(LTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lclave)
                    .addComponent(TClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombre)
                    .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellido)
                    .addComponent(TApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LApellido1)
                    .addComponent(TApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BEliminar)
                    .addComponent(BConsultar))
                .addGap(31, 31, 31)
                .addComponent(LTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(Bvolver3)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseClicked
  eliminarVenta();
    }//GEN-LAST:event_BEliminarMouseClicked

    private void Bvolver3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bvolver3MouseClicked
        Admin admin = new Admin(); 
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Bvolver3MouseClicked

    
    private void BConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConsultarMouseClicked
           consultarVentas();
    }//GEN-LAST:event_BConsultarMouseClicked

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange

    }//GEN-LAST:event_jTable1PropertyChange

    private void TClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TClaveActionPerformed

    private void TApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TApellidoActionPerformed

    private void TApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TApellido1ActionPerformed

    private void TNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton Bvolver3;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LApellido1;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LTexto;
    private javax.swing.JLabel Lclave;
    private javax.swing.JTextField TApellido;
    private javax.swing.JTextField TApellido1;
    private javax.swing.JTextField TClave;
    private javax.swing.JTextField TNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
