/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ameliafashion;

/**
 *
 * @author criss
 */
public class RegistroVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroVentas.class.getName());

    /**
     * Creates new form RegistroVentas
     */
    public RegistroVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TClave = new javax.swing.JTextField();
        LNombre = new javax.swing.JLabel();
        TNombre = new javax.swing.JTextField();
        LApellido = new javax.swing.JLabel();
        TApellido = new javax.swing.JTextField();
        LTexto = new javax.swing.JLabel();
        Lclave = new javax.swing.JLabel();
        BEliminar = new javax.swing.JButton();
        Bvolver3 = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LApellido1 = new javax.swing.JLabel();
        TApellido1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TClave.addActionListener(this::TClaveActionPerformed);

        LNombre.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LNombre.setForeground(new java.awt.Color(51, 153, 0));
        LNombre.setText("cantidad");

        TNombre.addActionListener(this::TNombreActionPerformed);

        LApellido.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LApellido.setForeground(new java.awt.Color(51, 153, 0));
        LApellido.setText("precio");

        TApellido.addActionListener(this::TApellidoActionPerformed);

        Lclave.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        Lclave.setForeground(new java.awt.Color(51, 153, 0));
        Lclave.setText("producto");

        BEliminar.setBackground(new java.awt.Color(102, 255, 102));
        BEliminar.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        BEliminar.setForeground(new java.awt.Color(51, 153, 0));
        BEliminar.setText("Eliminar");
        BEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEliminarMouseClicked(evt);
            }
        });
        BEliminar.addActionListener(this::BEliminarActionPerformed);

        Bvolver3.setBackground(new java.awt.Color(153, 255, 153));
        Bvolver3.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        Bvolver3.setForeground(new java.awt.Color(51, 153, 0));
        Bvolver3.setText("Volver");
        Bvolver3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bvolver3MouseClicked(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(102, 255, 102));
        BConsultar.setFont(new java.awt.Font("SimSun-ExtG", 1, 14)); // NOI18N
        BConsultar.setForeground(new java.awt.Color(51, 153, 0));
        BConsultar.setText("Consultar");
        BConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BConsultarMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "producto", "cant.", "precio", "fecha", "Total"
            }
        ));
        jTable1.addPropertyChangeListener(this::jTable1PropertyChange);
        jScrollPane1.setViewportView(jTable1);

        LApellido1.setFont(new java.awt.Font("SimSun-ExtG", 1, 18)); // NOI18N
        LApellido1.setForeground(new java.awt.Color(51, 153, 0));
        LApellido1.setText("fecha");

        TApellido1.addActionListener(this::TApellido1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(LNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TClave, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(115, 115, 115)
                                    .addComponent(Lclave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(163, 163, 163))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(BEliminar)
                                            .addGap(64, 64, 64)
                                            .addComponent(BConsultar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(LApellido)
                                                .addComponent(LApellido1))
                                            .addGap(163, 163, 163)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Bvolver3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(LTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lclave)
                            .addComponent(TClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNombre)
                            .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LApellido)
                            .addComponent(TApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LApellido1)
                            .addComponent(TApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BEliminar)
                            .addComponent(BConsultar))
                        .addGap(46, 46, 46)
                        .addComponent(LTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(Bvolver3)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TClaveActionPerformed

    private void TNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNombreActionPerformed

    private void TApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TApellidoActionPerformed

    private void BEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEliminarMouseClicked
 
    }//GEN-LAST:event_BEliminarMouseClicked

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BEliminarActionPerformed

    private void Bvolver3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bvolver3MouseClicked
        Inicio ventana = new Inicio();
        ventana.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_Bvolver3MouseClicked

    private void BConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BConsultarMouseClicked
   
    }//GEN-LAST:event_BConsultarMouseClicked

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange

    }//GEN-LAST:event_jTable1PropertyChange

    private void TApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TApellido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton Bvolver;
    private javax.swing.JButton Bvolver1;
    private javax.swing.JButton Bvolver2;
    private javax.swing.JButton Bvolver3;
    private javax.swing.JLabel LApellido;
    private javax.swing.JLabel LApellido1;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LTexto;
    private javax.swing.JLabel Lclave;
    private javax.swing.JTextField TApellido;
    private javax.swing.JTextField TApellido1;
    private javax.swing.JTextField TClave;
    private javax.swing.JTextField TNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
